spring.application.name=vitaltacc

spring.datasource.url=jdbc:mysql://localhost:3306/basevitaltacc
spring.datasource.username=root
spring.datasource.password=juanga438197

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

